name: Upload Ubuntu Python tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-24.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache_ubuntu_v4.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache_ubuntu_v4.tar.gz
